### PR TITLE
First version of TaskScheduler

### PR DESCRIPTION
**Pull request by martap**
First version. 
TODO:
1. "demo" page 
2. double check all described  algorithm steps.

### CODE REVIEW

**Comment by martap** [comment]
Ok, it is ready for review. Basic tests are done. @marcoscaceres please check if you have any comments. 
I hope it works fine ( if not, this means that the heat 30C shut down my brain )

**Comment by marcoscaceres** [comment]
Spoke to @martap, she is making some changes to this before we review/merge.

**Comment by martap** [comment]
Version ready to check.

I get page build errors (page works fine on my local server), but I do not know how to overcome this, any help will be appreciated :)

**Comment by martap** [comment]
Please do not merge this pull request, I had to create new branch after rebase (I has it already on server) so I've pull request new rebased version

**Pull request closed without merging**
